name: setup-yarn

inputs:
  AUTH_TOKEN:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    # Yarn2+ ignores the github action .npmrc and .yarnrc, so we have to manually set that up
    # see https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#yarn2-configuration
    - name: setup .yarnrc.yml
      run: |
        yarn config set npmRegistryServer "https://registry.npmjs.org"
        yarn config set npmAlwaysAuth true
        yarn config set npmAuthToken ${{inputs.AUTH_TOKEN}}
      shell: bash
    # fixing yarn cache, see https://github.com/actions/setup-node/issues/488
    - name: get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      shell: bash
    - name: restore yarn cache
      uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: yarn-cache-folder-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}
        restore-keys: |
          yarn-cache-folder-
    - name: install dependencies
      run: yarn install --immutable
      shell: bash
